menu:
  主页:
  归档: archives
  RSS: atom.xml

widgets:
# - search
- category
- tag
- recent_posts 

excerpt_link: 阅读全文 #<!-- more -->

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: true

fancybox: true

google_analytics:
rss: atom.xml

# comment_provider: facebook
# # Facebook comment
# facebook:
#   appid: 123456789012345
#   comment_count: 5
#   comment_width: 840
#   comment_colorscheme: light
valine:
  enable: true
  appId:  kmMKqkSXWWEaldKSpO4w43aM-gzGzoHsz
  appKey: Ligl9mlWd0n0Iu1E2yXUGXQa
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊! 
  guest_info: nick,mail,link
  pageSize: 10
